/* =========================================================
   RECIPE DATA
   ---------------------------------------------------------
   To add a new recipe, append an object to the RECIPES array.
   Fields:
     id            unique kebab-case string
     title         recipe name
     tagline       one-line description
     icon          one of: watermelon, paneer, cake, blank, jar,
                   fritter, spice, dijonjar
     accent        PALETTE.brick | PALETTE.basil | PALETTE.mustard
     baseServings  number the amounts below are written for
     sourceUrl     (optional) reference link
     allergens     (optional) string, e.g. "Milk · Eggs · Wheat"
     ingredients   [{ id, amount, unit, name }]
     steps         [{ id, title, content, timer }]  timer = seconds or null
     notes         (optional) free text
   ========================================================= */

const PALETTE = {
  paper: "#F7F3EA",
  paperDark: "#EDE6D6",
  ink: "#2B3226",
  inkSoft: "#5B6355",
  basil: "#4B6A45",
  basilDark: "#37502F",
  brick: "#B4472F",
  mustard: "#D2A03D",
  line: "#D8CFB8",
};

const RECIPES = [
  {
    id: "watermelon-feta-mint",
    title: "Watermelon Feta Mint Salad",
    tagline: "Cool, sweet-salty, and built for a 100° afternoon.",
    icon: "watermelon",
    accent: PALETTE.brick,
    baseServings: 9,
    ingredients: [
      { id: "i1", amount: 2.5, unit: "kg", name: "seedless watermelon, cubed" },
      { id: "i2", amount: 2, unit: "", name: "English cucumbers, thinly sliced" },
      { id: "i3", amount: 300, unit: "g", name: "feta cheese, crumbled" },
      { id: "i4", amount: 0.5, unit: "", name: "red onion, thinly sliced" },
      { id: "i5", amount: 0.75, unit: "cup", name: "fresh mint leaves, torn" },
      { id: "i6", amount: 3, unit: "", name: "limes, juiced" },
      { id: "i7", amount: 3, unit: "tbsp", name: "extra virgin olive oil" },
      { id: "i8", amount: 0.5, unit: "tsp", name: "flaky salt" },
      { id: "i9", amount: 0.25, unit: "tsp", name: "black pepper, cracked" },
      { id: "i10", amount: 0.5, unit: "cup", name: "pomegranate seeds, thawed & drained (optional)" },
    ],
    steps: [
      { id: "s1", title: "Prep the fruit & veg", content: "Cube the watermelon and slice the cucumber and red onion. Keep everything cold.", timer: null },
      { id: "s2", title: "Make the dressing", content: "Whisk together lime juice, olive oil, salt, and pepper.", timer: null },
      { id: "s3", title: "Assemble", content: "In a wide serving bowl, gently combine watermelon, cucumber, and red onion. Drizzle with dressing and toss gently.", timer: null },
      { id: "s4", title: "Top & serve", content: "Scatter feta, mint, and pomegranate seeds on top right before serving. Serve chilled.", timer: null },
    ],
    notes: "Don't add feta/mint until close to serving — salt draws out watermelon juice fast in the heat. Keep on ice until guests arrive. Serve arugula on the side for guests to add themselves.",
  },
  {
    id: "paneer-chickpea",
    title: "Crispy Paneer Chickpea Salad",
    tagline: "Griddled paneer, lemon-cumin dressing, built to share the grill.",
    icon: "paneer",
    accent: PALETTE.basil,
    baseServings: 9,
    ingredients: [
      { id: "i1", amount: 500, unit: "g", name: "paneer, cubed" },
      { id: "i2", amount: 2, unit: "cup", name: "chickpeas, drained and rinsed" },
      { id: "i3", amount: 2, unit: "", name: "cucumbers, diced" },
      { id: "i4", amount: 3, unit: "cup", name: "cherry tomatoes, halved" },
      { id: "i5", amount: 1, unit: "", name: "red bell pepper, diced" },
      { id: "i6", amount: 0.5, unit: "cup", name: "fresh cilantro, chopped" },
      { id: "i7", amount: 2, unit: "tbsp", name: "olive oil (for marinating paneer)" },
      { id: "i8", amount: 1.5, unit: "tsp", name: "ground cumin" },
      { id: "i9", amount: 1, unit: "tsp", name: "smoked paprika" },
      { id: "i10", amount: 3, unit: "cloves", name: "garlic, minced (divided)" },
      { id: "i11", amount: 2, unit: "", name: "lemons, juiced" },
      { id: "i12", amount: 4, unit: "tbsp", name: "olive oil (for dressing)" },
      { id: "i13", amount: 1, unit: "tsp", name: "salt" },
      { id: "i14", amount: 0.75, unit: "cup", name: "pomegranate seeds, thawed & drained (optional)" },
    ],
    steps: [
      { id: "s1", title: "Marinate the paneer", content: "Toss paneer with olive oil, cumin, smoked paprika, and half the garlic.", timer: 900 },
      { id: "s2", title: "Griddle the paneer", content: "Sear on a hot griddle 2–3 minutes per side until golden and lightly crisp. Set aside.", timer: null },
      { id: "s3", title: "Prep the vegetables", content: "Dice cucumber and bell pepper, halve tomatoes, chop cilantro.", timer: null },
      { id: "s4", title: "Make the dressing", content: "Whisk lemon juice, olive oil, salt, and remaining garlic.", timer: null },
      { id: "s5", title: "Assemble", content: "Combine chickpeas, cucumber, tomatoes, bell pepper, and cilantro. Add dressing and toss.", timer: null },
      { id: "s6", title: "Top & serve", content: "Top with warm paneer and pomegranate seeds just before serving.", timer: null },
    ],
    notes: "Griddle the paneer right alongside the burgers — no separate pan needed. Prep the base ahead; griddle the paneer close to serving so it stays crisp. Serve arugula on the side for guests to add themselves.",
  },
  {
    id: "peach-eierlikortorte",
    title: "No-Bake Peach Eierlikörtorte",
    tagline: "German ladyfinger torte, peach & mascarpone cream, no oven needed.",
    icon: "cake",
    accent: PALETTE.mustard,
    baseServings: 12,
    sourceUrl: "https://youtu.be/3-3LOFvH4GE",
    ingredients: [
      { id: "i1", amount: 2, unit: "", name: "packages ladyfingers (Savoiardi), about 24 total" },
      { id: "i2", amount: 2, unit: "cans", name: "canned peach halves (29 oz), well drained, juice reserved" },
      { id: "i3", amount: 500, unit: "ml", name: "heavy whipping cream" },
      { id: "i4", amount: 500, unit: "g", name: "mascarpone, room temperature" },
      { id: "i5", amount: 150, unit: "g", name: "powdered sugar" },
      { id: "i6", amount: 1, unit: "tsp", name: "vanilla extract (added to the mascarpone mixture)" },
      { id: "i7", amount: 3, unit: "packets", name: "unflavored gelatin (2¼ tsp each)" },
      { id: "i8", amount: 6, unit: "tbsp", name: "cold water (to bloom gelatin)" },
      { id: "i9", amount: 0.5, unit: "cup", name: "reserved peach juice, for soaking ladyfingers" },
      { id: "i10", amount: 0.5, unit: "cup", name: "slivered almonds, toasted" },
    ],
    steps: [
      { id: "s1", title: "Bloom the gelatin", content: "Sprinkle gelatin over cold water. Let sit 5–10 min, then gently melt until liquid. Cool slightly but don't let it set.", timer: 600 },
      { id: "s2", title: "Toast the almonds", content: "Toast slivered almonds in a dry pan over medium heat, 3–4 minutes, stirring often until golden and fragrant. Set aside to cool.", timer: 240 },
      { id: "s3", title: "Prep the peaches", content: "Dice about two-thirds of the drained peaches; keep the rest as slices for the top.", timer: null },
      { id: "s4", title: "Make the cream filling", content: "Whip cream to soft peaks. Separately beat mascarpone, powdered sugar, and vanilla extract until smooth, then fold in the whipped cream.", timer: null },
      { id: "s5", title: "Add gelatin & peaches", content: "Drizzle the cooled melted gelatin into the cream while folding continuously. Fold in the diced peaches.", timer: null },
      { id: "s6", title: "Line the pan", content: "Line a 9-inch springform with ladyfingers, briefly dipping each in reserved peach juice.", timer: null },
      { id: "s7", title: "Layer the cake", content: "Pour in half the filling, add a middle layer of soaked ladyfingers, then top with remaining filling and smooth.", timer: null },
      { id: "s8", title: "Top & chill", content: "Arrange peach slices on top and scatter the toasted almonds over everything. Cover and refrigerate until fully set — overnight is best.", timer: 18000 },
      { id: "s9", title: "Release & slice", content: "Run a thin knife around the edge before releasing the springform. Use a clean knife between cuts for neat layers.", timer: null },
    ],
    notes: "Make this the day before — it needs at least 5 hours to set, and the flavor is even better after a full night in the fridge. Lay the ladyfingers whole (don't crush them) so the layers stay clean when sliced — no need to pre-bake them, they're meant to soften from the peach juice.",
  },
  {
    id: "paneer-kimchi-egg-bowl",
    title: "Crispy Paneer & Kimchi Fried Egg Bowl",
    tagline: "Golden seared paneer, garlicky kimchi, and a crispy fried egg over a bright herb salad.",
    icon: "blank",
    accent: PALETTE.brick,
    baseServings: 2,
    ingredients: [
      { id: "i1", amount: 8, unit: "oz", name: "paneer, cubed" },
      { id: "i2", amount: 2, unit: "tbsp", name: "neutral oil" },
      { id: "i3", amount: 1, unit: "cup", name: "kimchi, chopped" },
      { id: "i4", amount: 2, unit: "", name: "garlic cloves, minced" },
      { id: "i5", amount: 1, unit: "", name: "Fresno chili, sliced" },
      { id: "i6", amount: 2, unit: "", name: "large eggs" },
      { id: "i7", amount: 3, unit: "cup", name: "spring mix" },
      { id: "i8", amount: 1, unit: "cup", name: "cherry tomatoes, halved" },
      { id: "i9", amount: 2, unit: "tbsp", name: "parsley, chopped" },
      { id: "i10", amount: 2, unit: "tbsp", name: "olive oil" },
      { id: "i11", amount: 1, unit: "tbsp", name: "rice vinegar or kimchi juice" },
      { id: "i12", amount: 1, unit: "tsp", name: "soy sauce" },
      { id: "i13", amount: 0.25, unit: "tsp", name: "salt" },
    ],
    steps: [
      { id: "s1", title: "Season & sear the paneer", content: "Toss cubed paneer with a little oil, salt, garlic powder, and smoked paprika. Heat neutral oil in a nonstick pan over medium-high heat and sear, turning occasionally, until golden and crispy on all sides.", timer: 480 },
      { id: "s2", title: "Sauté kimchi", content: "In the same pan, add garlic and Fresno chili, cook 1 minute until fragrant. Add kimchi and sauté until warmed through and slightly caramelized.", timer: 240 },
      { id: "s3", title: "Fry the eggs", content: "In a separate pan, fry eggs sunny-side up until whites are set and edges are crispy.", timer: 180 },
      { id: "s4", title: "Toss the salad", content: "Combine spring mix, cherry tomatoes, and parsley. Dress with olive oil, rice vinegar, soy sauce, and salt.", timer: null },
      { id: "s5", title: "Assemble", content: "Divide dressed salad between bowls. Top with sautéed kimchi, crispy paneer, and a fried egg. Serve immediately.", timer: null },
    ],
    notes: "Frozen pomegranate seeds scattered on top add a nice sweet-tart crunch if you want to dress it up. Mini cucumbers, sliced thin, are a good addition to the salad too (about 3 mini per English cucumber). For a different direction, swap the garlic powder/smoked paprika for gochugaru, or for garam masala and cumin.",
  },
  {
    id: "fresh-herb-ranch",
    title: "Fresh Herb Ranch Dressing",
    tagline: "Buttermilk ranch thinned out with minced fresh dill, chives & parsley.",
    icon: "jar",
    accent: PALETTE.basil,
    baseServings: 6,
    ingredients: [
      { id: "i1", amount: 0.75, unit: "cup", name: "buttermilk" },
      { id: "i2", amount: 0.5, unit: "cup", name: "mayonnaise" },
      { id: "i3", amount: 0.25, unit: "cup", name: "sour cream" },
      { id: "i4", amount: 1, unit: "tsp", name: "lemon juice" },
      { id: "i5", amount: 1, unit: "tbsp", name: "fresh dill, finely minced" },
      { id: "i6", amount: 1, unit: "tbsp", name: "fresh chives, finely minced" },
      { id: "i7", amount: 1, unit: "tbsp", name: "fresh parsley, finely minced" },
      { id: "i8", amount: 0.5, unit: "tsp", name: "garlic powder" },
      { id: "i9", amount: 0.5, unit: "tsp", name: "onion powder" },
      { id: "i10", amount: 0.5, unit: "tsp", name: "salt" },
      { id: "i11", amount: 0.5, unit: "tsp", name: "black pepper" },
    ],
    steps: [
      { id: "s1", title: "Whisk the liquids", content: "Combine buttermilk, mayonnaise, sour cream, and lemon juice in a bowl.", timer: null },
      { id: "s2", title: "Prep the herbs", content: "Finely mince the fresh dill, chives, and parsley so they distribute evenly.", timer: null },
      { id: "s3", title: "Blend everything", content: "Stir the fresh herbs and dry spices (garlic powder, onion powder, salt, pepper) into the liquid base.", timer: null },
      { id: "s4", title: "Check the thickness", content: "If you want it even thinner, whisk in an extra tablespoon of buttermilk.", timer: null },
      { id: "s5", title: "Rest & chill", content: "Chill in the fridge to let the fresh herb oils infuse before serving.", timer: 1800 },
    ],
    notes: "Fresh herbs are less concentrated than dried — that's why the quantities here run about triple what a dried-herb ranch would use, to keep the flavor vibrant. For a bolder version, try swapping the garlic powder for fresh minced garlic.",
  },
  {
    id: "broccoli-cheddar-fritters",
    title: "Crispy Broccoli Cheddar Fritters with Ranch Salad",
    tagline: "Golden fried fritters, honey Dijon for dipping, ranch salad with pickled shallot on the side.",
    icon: "fritter",
    accent: PALETTE.mustard,
    baseServings: 2,
    allergens: "Milk · Eggs · Wheat",
    ingredients: [
      { id: "i1", amount: 8, unit: "oz", name: "broccoli, florets and stalks minced" },
      { id: "i2", amount: 0.5, unit: "cup", name: "cheddar cheese, shredded" },
      { id: "i3", amount: 82, unit: "g", name: "tempura batter mix" },
      { id: "i4", amount: 1, unit: "tbsp", name: "flour" },
      { id: "i5", amount: 1, unit: "tbsp", name: "Fry Seasoning" },
      { id: "i6", amount: 1, unit: "", name: "shallot, halved, peeled & thinly sliced" },
      { id: "i7", amount: 5, unit: "tsp", name: "white wine vinegar" },
      { id: "i8", amount: 0.5, unit: "tsp", name: "sugar" },
      { id: "i9", amount: 1, unit: "", name: "tomato, diced" },
      { id: "i10", amount: 4, unit: "oz", name: "mixed greens" },
      { id: "i11", amount: 3, unit: "oz", name: "buttermilk ranch dressing" },
      { id: "i12", amount: 1.5, unit: "oz", name: "honey Dijon dressing, for dipping" },
      { id: "i13", amount: 2, unit: "tsp", name: "cooking oil, plus more for frying" },
      { id: "i14", amount: 1, unit: "tsp", name: "salt, plus more to taste" },
      { id: "i15", amount: 0.25, unit: "tsp", name: "black pepper, plus more to taste" },
    ],
    steps: [
      { id: "s1", title: "Prep the broccoli", content: "Wash and dry produce. Mince the broccoli florets and stalks. Place in a large microwave-safe bowl with 1 tbsp water, cover with plastic wrap, and microwave until bright green and slightly softened, 2–3 minutes. Halve, peel, and thinly slice the shallot crosswise. Dice the tomato.", timer: 180 },
      { id: "s2", title: "Quick-pickle the shallot", content: "In a small bowl, combine the sliced shallot, vinegar, sugar, and a pinch of salt. Cover with plastic wrap and microwave 30 seconds. Set aside to pickle, stirring occasionally, until ready to use.", timer: 30 },
      { id: "s3", title: "Mix the fritter batter", content: "In a second large bowl, combine tempura batter mix, flour, Fry Seasoning, 1/3 cup cold water, 1/2 tsp salt, and pepper until smooth. Stir in the broccoli and cheddar until thoroughly combined.", timer: null },
      { id: "s4", title: "Fry the fritters", content: "Heat a large drizzle of oil in a large pan over medium-high heat. Once hot, add 1/4-cup scoops of fritter batter and cook until browned, crisped, and warmed through, 2–4 minutes per side. Don't overcrowd the pan — cook in batches if needed, and lower the heat if they're browning too fast. Transfer to a paper-towel-lined plate and season immediately with salt. Wash and dry the batter bowl.", timer: 240 },
      { id: "s5", title: "Toss the ranch salad", content: "In the bowl used for the fritter batter, toss together the mixed greens, tomato, pickled shallot (draining it first), and buttermilk ranch dressing. Season with salt and pepper.", timer: null },
      { id: "s6", title: "Plate & serve", content: "Divide the salad and fritters between plates. Serve with honey Dijon dressing on the side for dipping.", timer: null },
    ],
    notes: "Allergens: milk, eggs, wheat. Uses the Fry Seasoning and Honey Dijon Dressing recipes also in this cookbook.",
  },
  {
    id: "fry-seasoning",
    title: "Fry Seasoning (Copycat Blend)",
    tagline: "Smoky paprika-garlic-onion blend for fries, roasted veg, and fritters.",
    icon: "spice",
    accent: PALETTE.brick,
    baseServings: 6,
    ingredients: [
      { id: "i1", amount: 2, unit: "tbsp", name: "smoked paprika" },
      { id: "i2", amount: 2, unit: "tbsp", name: "garlic powder" },
      { id: "i3", amount: 2, unit: "tbsp", name: "onion powder" },
      { id: "i4", amount: 1, unit: "tsp", name: "ground cumin (optional)" },
      { id: "i5", amount: 0.5, unit: "tsp", name: "ground coriander (optional)" },
      { id: "i6", amount: 0.25, unit: "tsp", name: "cayenne pepper (optional, for heat)" },
    ],
    steps: [
      { id: "s1", title: "Measure the base", content: "Measure the smoked paprika, garlic powder, and onion powder into a small bowl.", timer: null },
      { id: "s2", title: "Add optional depth", content: "Stir in cumin, coriander, and/or cayenne if using, for a warmer or spicier blend.", timer: null },
      { id: "s3", title: "Whisk to combine", content: "Whisk everything together until evenly combined, breaking up any clumps.", timer: null },
      { id: "s4", title: "Store", content: "Transfer to an airtight jar or container. Keeps up to 6 months in a cool, dark pantry.", timer: null },
    ],
    notes: "This is a homemade stand-in for HelloFresh's proprietary Fry Seasoning — they don't publish the exact ratio, but it's built around paprika, garlic powder, and onion powder. Use about 1 tbsp per 1.5 lbs of potatoes or vegetables before roasting or air frying. Used in the broccoli cheddar fritters recipe.",
  },
  {
    id: "honey-dijon-dressing",
    title: "Honey Dijon Dressing",
    tagline: "Whisked mustard-honey vinaigrette, ready in five minutes.",
    icon: "dijonjar",
    accent: PALETTE.mustard,
    baseServings: 6,
    ingredients: [
      { id: "i1", amount: 0.25, unit: "cup", name: "Dijon mustard" },
      { id: "i2", amount: 0.25, unit: "cup", name: "honey" },
      { id: "i3", amount: 2, unit: "tbsp", name: "apple cider vinegar (or lemon juice)" },
      { id: "i4", amount: 0.33, unit: "cup", name: "olive oil" },
      { id: "i5", amount: 0.25, unit: "tsp", name: "salt" },
      { id: "i6", amount: 0.25, unit: "tsp", name: "black pepper" },
    ],
    steps: [
      { id: "s1", title: "Whisk the base", content: "Whisk together Dijon mustard, honey, and apple cider vinegar until smooth.", timer: null },
      { id: "s2", title: "Emulsify the oil", content: "Slowly drizzle in the olive oil while whisking continuously, so it emulsifies instead of separating.", timer: null },
      { id: "s3", title: "Season & taste", content: "Season with salt and pepper. Taste and adjust — more honey for sweeter, more vinegar for tang.", timer: null },
      { id: "s4", title: "Store", content: "Keep in a sealed jar in the fridge for up to a week. Give it a shake before using, since it can separate slightly when cold.", timer: null },
    ],
    notes: "Makes about 3/4 cup. Doubles nicely as both a dressing and a dip — it's the dipping sauce for the broccoli cheddar fritters recipe.",
  },
];
