/* =========================================================
   RECIPE DATA
   ---------------------------------------------------------
   To add a new recipe, append an object to the RECIPES array.
   Fields:
     id            unique kebab-case string
     title         recipe name
     tagline       one-line description
     category      one of the strings in CATEGORIES below
     icon          one of: watermelon, paneer, cake, blank, jar,
                   fritter, spice, dijonjar
     accent        PALETTE.brick | PALETTE.basil | PALETTE.mustard
     baseServings  number the amounts below are written for (or the
                   total yield, when scalable is false)
     scalable      (optional) set to false for a yield/batch recipe
                   (a whole cake, a jar of dressing, a spice blend) —
                   hides the servings stepper and shows a plain
                   "MAKES {baseServings}" label instead
     sourceUrl     (optional) reference link
     allergens     (optional) string, e.g. "Milk · Eggs · Wheat"
     image         (optional) sample photo URL shown on the card + detail page
     imageCredit   (optional) { name, username } — Unsplash photographer credit
     ingredients   [{ id, amount, unit, name }]
     steps         [{ id, title, content, timer }]  timer = seconds or null
     notes         (optional) free text
   ========================================================= */

const CATEGORIES = ["Salads", "Mains", "Dressings & Sauces", "Seasonings", "Desserts"];

const PALETTE = {
  paper: "#F7F3EA",
  paperDark: "#EDE6D6",
  ink: "#2B3226",
  inkSoft: "#5B6355",
  basil: "#4B6A45",
  basilDark: "#37502F",
  brick: "#B4472F",
  mustard: "#D2A03D",
  line: "#D8CFB8",
};

const RECIPES = [
  {
    id: "watermelon-feta-mint",
    title: "Watermelon Feta Mint Salad",
    tagline: "Cool, sweet-salty, and built for a 100° afternoon.",
    category: "Salads",
    icon: "watermelon",
    accent: PALETTE.brick,
    baseServings: 9,
    image: "https://images.unsplash.com/photo-1626303551646-69dbd1ab24be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8d2F0ZXJtZWxvbiUyMGZldGElMjBzYWxhZHxlbnwwfDB8fHwxNzg2OTM0MDMyfDI&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Anto Meneghini", username: "antomeneghini" },
    ingredients: [
      { id: "i1", amount: 2.5, unit: "kg", name: "seedless watermelon, cubed" },
      { id: "i2", amount: 2, unit: "", name: "English cucumbers, thinly sliced" },
      { id: "i3", amount: 300, unit: "g", name: "feta cheese, crumbled" },
      { id: "i4", amount: 0.5, unit: "", name: "red onion, thinly sliced" },
      { id: "i5", amount: 0.75, unit: "cup", name: "fresh mint leaves, torn" },
      { id: "i6", amount: 3, unit: "", name: "limes, juiced" },
      { id: "i7", amount: 3, unit: "tbsp", name: "extra virgin olive oil" },
      { id: "i8", amount: 0.5, unit: "tsp", name: "flaky salt" },
      { id: "i9", amount: 0.25, unit: "tsp", name: "black pepper, cracked" },
      { id: "i10", amount: 0.5, unit: "cup", name: "pomegranate seeds, thawed & drained (optional)" },
    ],
    steps: [
      { id: "s1", title: "Prep the fruit & veg", content: "Cube the 2.5 kg watermelon and thinly slice the 2 cucumbers and ½ red onion. Keep everything cold.", timer: null },
      { id: "s2", title: "Make the dressing", content: "Whisk together the juice of 3 limes, 3 tbsp olive oil, ½ tsp flaky salt, and ¼ tsp cracked black pepper.", timer: null },
      { id: "s3", title: "Assemble", content: "In a wide serving bowl, gently combine the watermelon, cucumber, and red onion. Drizzle with the dressing and toss gently.", timer: null },
      { id: "s4", title: "Top & serve", content: "Scatter the 300 g feta, ¾ cup mint, and ½ cup pomegranate seeds (if using) on top right before serving. Serve chilled.", timer: null },
    ],
    notes: "Don't add feta/mint until close to serving — salt draws out watermelon juice fast in the heat. Keep on ice until guests arrive. Serve arugula on the side for guests to add themselves.",
  },
  {
    id: "paneer-chickpea",
    title: "Crispy Paneer Chickpea Salad",
    tagline: "Griddled paneer, lemon-cumin dressing, built to share the grill.",
    category: "Salads",
    icon: "paneer",
    accent: PALETTE.basil,
    baseServings: 9,
    image: "https://images.unsplash.com/photo-1608032077018-c9aad9565d29?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8Z3JpbGxlZCUyMHBhbmVlciUyMHNhbGFkfGVufDB8MHx8fDE3ODY5MzQwMzN8Mg&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Christine Isakzhanova", username: "bulochka" },
    ingredients: [
      { id: "i1", amount: 500, unit: "g", name: "paneer, cubed" },
      { id: "i2", amount: 2, unit: "cup", name: "chickpeas, drained and rinsed" },
      { id: "i3", amount: 2, unit: "", name: "cucumbers, diced" },
      { id: "i4", amount: 3, unit: "cup", name: "cherry tomatoes, halved" },
      { id: "i5", amount: 1, unit: "", name: "red bell pepper, diced" },
      { id: "i6", amount: 0.5, unit: "cup", name: "fresh cilantro, chopped" },
      { id: "i7", amount: 2, unit: "tbsp", name: "olive oil (for marinating paneer)" },
      { id: "i8", amount: 1.5, unit: "tsp", name: "ground cumin" },
      { id: "i9", amount: 1, unit: "tsp", name: "smoked paprika" },
      { id: "i10", amount: 3, unit: "cloves", name: "garlic, minced (divided)" },
      { id: "i11", amount: 2, unit: "", name: "lemons, juiced" },
      { id: "i12", amount: 4, unit: "tbsp", name: "olive oil (for dressing)" },
      { id: "i13", amount: 1, unit: "tsp", name: "salt" },
      { id: "i14", amount: 0.75, unit: "cup", name: "pomegranate seeds, thawed & drained (optional)" },
    ],
    steps: [
      { id: "s1", title: "Marinate the paneer", content: "Toss the 500 g paneer with 2 tbsp olive oil, 1½ tsp ground cumin, 1 tsp smoked paprika, and half the minced garlic (about 1½ cloves).", timer: 900 },
      { id: "s2", title: "Griddle the paneer", content: "Sear on a hot griddle 2–3 minutes per side until golden and lightly crisp. Set aside.", timer: null },
      { id: "s3", title: "Prep the vegetables", content: "Dice the 2 cucumbers and red bell pepper, halve the 3 cups cherry tomatoes, and chop the ½ cup cilantro.", timer: null },
      { id: "s4", title: "Make the dressing", content: "Whisk the juice of 2 lemons with 4 tbsp olive oil, 1 tsp salt, and the remaining garlic.", timer: null },
      { id: "s5", title: "Assemble", content: "Combine the 2 cups chickpeas, cucumber, tomatoes, bell pepper, and cilantro. Add the dressing and toss.", timer: null },
      { id: "s6", title: "Top & serve", content: "Top with the warm paneer and ¾ cup pomegranate seeds (if using) just before serving.", timer: null },
    ],
    notes: "Griddle the paneer right alongside the burgers — no separate pan needed. Prep the base ahead; griddle the paneer close to serving so it stays crisp. Serve arugula on the side for guests to add themselves.",
  },
  {
    id: "peach-eierlikortorte",
    title: "No-Bake Peach Eierlikörtorte",
    tagline: "German ladyfinger torte, peach & mascarpone cream, no oven needed.",
    category: "Desserts",
    icon: "cake",
    accent: PALETTE.mustard,
    baseServings: 12,
    scalable: false,
    sourceUrl: "https://youtu.be/3-3LOFvH4GE",
    image: "images/peach-eierlikortorte.jpg",
    ingredients: [
      { id: "i1", amount: 2, unit: "", name: "packages ladyfingers (Savoiardi), about 24 total" },
      { id: "i2", amount: 2, unit: "cans", name: "canned peach halves (29 oz), well drained, juice reserved" },
      { id: "i3", amount: 500, unit: "ml", name: "heavy whipping cream" },
      { id: "i4", amount: 500, unit: "g", name: "mascarpone, room temperature" },
      { id: "i5", amount: 150, unit: "g", name: "powdered sugar" },
      { id: "i6", amount: 1, unit: "tsp", name: "vanilla extract (added to the mascarpone mixture)" },
      { id: "i7", amount: 3, unit: "packets", name: "unflavored gelatin (2¼ tsp each)" },
      { id: "i8", amount: 6, unit: "tbsp", name: "cold water (to bloom gelatin)" },
      { id: "i9", amount: 0.5, unit: "cup", name: "reserved peach juice, for soaking ladyfingers" },
      { id: "i10", amount: 0.5, unit: "cup", name: "slivered almonds, toasted" },
    ],
    steps: [
      { id: "s1", title: "Bloom the gelatin", content: "Sprinkle the 3 packets gelatin over 6 tbsp cold water. Let sit 5–10 min, then gently melt until liquid. Cool slightly but don't let it set.", timer: 600 },
      { id: "s2", title: "Toast the almonds", content: "Toast the ½ cup slivered almonds in a dry pan over medium heat, 3–4 minutes, stirring often until golden and fragrant. Set aside to cool.", timer: 240 },
      { id: "s3", title: "Prep the peaches", content: "Dice about two-thirds of the drained peaches (from the 2 cans); keep the rest as slices for the top.", timer: null },
      { id: "s4", title: "Make the cream filling", content: "Whip the 500 ml heavy cream to soft peaks. Separately beat the 500 g mascarpone, 150 g powdered sugar, and 1 tsp vanilla extract until smooth, then fold in the whipped cream.", timer: null },
      { id: "s5", title: "Add gelatin & peaches", content: "Drizzle the cooled melted gelatin into the cream while folding continuously. Fold in the diced peaches.", timer: null },
      { id: "s6", title: "Line the pan", content: "Line a 9-inch springform with the ladyfingers (from the 2 packages), briefly dipping each in the ½ cup reserved peach juice.", timer: null },
      { id: "s7", title: "Layer the cake", content: "Pour in half the filling, add a middle layer of soaked ladyfingers, then top with remaining filling and smooth.", timer: null },
      { id: "s8", title: "Top & chill", content: "Arrange the reserved peach slices on top and scatter the toasted almonds over everything. Cover and refrigerate until fully set — overnight is best.", timer: 18000 },
      { id: "s9", title: "Release & slice", content: "Run a thin knife around the edge before releasing the springform. Use a clean knife between cuts for neat layers.", timer: null },
    ],
    notes: "Make this the day before — it needs at least 5 hours to set, and the flavor is even better after a full night in the fridge. Lay the ladyfingers whole (don't crush them) so the layers stay clean when sliced — no need to pre-bake them, they're meant to soften from the peach juice.",
  },
  {
    id: "paneer-kimchi-egg-bowl",
    title: "Crispy Paneer & Kimchi Fried Egg Bowl",
    tagline: "Golden seared paneer, garlicky kimchi, and a crispy fried egg over a bright herb salad.",
    category: "Mains",
    icon: "blank",
    accent: PALETTE.brick,
    baseServings: 2,
    image: "https://images.unsplash.com/photo-1600688654899-379ec76aca42?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8ZnJpZWQlMjBlZ2clMjByaWNlJTIwYm93bHxlbnwwfDB8fHwxNzg2OTM0MDM0fDI&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Emanuel Ekström", username: "emanuelekstrom" },
    ingredients: [
      { id: "i1", amount: 8, unit: "oz", name: "paneer, cubed" },
      { id: "i2", amount: 2, unit: "tbsp", name: "neutral oil" },
      { id: "i3", amount: 1, unit: "cup", name: "kimchi, chopped" },
      { id: "i4", amount: 2, unit: "", name: "garlic cloves, minced" },
      { id: "i5", amount: 1, unit: "", name: "Fresno chili, sliced" },
      { id: "i6", amount: 2, unit: "", name: "large eggs" },
      { id: "i7", amount: 3, unit: "cup", name: "spring mix" },
      { id: "i8", amount: 1, unit: "cup", name: "cherry tomatoes, halved" },
      { id: "i9", amount: 2, unit: "tbsp", name: "parsley, chopped" },
      { id: "i10", amount: 2, unit: "tbsp", name: "olive oil" },
      { id: "i11", amount: 1, unit: "tbsp", name: "rice vinegar or kimchi juice" },
      { id: "i12", amount: 1, unit: "tsp", name: "soy sauce" },
      { id: "i13", amount: 0.25, unit: "tsp", name: "salt" },
    ],
    steps: [
      { id: "s1", title: "Season & sear the paneer", content: "Toss the 8 oz cubed paneer with a little oil, salt, garlic powder, and smoked paprika. Heat 2 tbsp neutral oil in a nonstick pan over medium-high heat and sear, turning occasionally, until golden and crispy on all sides.", timer: 480 },
      { id: "s2", title: "Sauté kimchi", content: "In the same pan, add the 2 minced garlic cloves and 1 sliced Fresno chili, cook 1 minute until fragrant. Add the 1 cup kimchi and sauté until warmed through and slightly caramelized.", timer: 240 },
      { id: "s3", title: "Fry the eggs", content: "In a separate pan, fry the 2 eggs sunny-side up until whites are set and edges are crispy.", timer: 180 },
      { id: "s4", title: "Toss the salad", content: "Combine the 3 cups spring mix, 1 cup cherry tomatoes, and 2 tbsp parsley. Dress with 2 tbsp olive oil, 1 tbsp rice vinegar, 1 tsp soy sauce, and ¼ tsp salt.", timer: null },
      { id: "s5", title: "Assemble", content: "Divide dressed salad between bowls. Top with sautéed kimchi, crispy paneer, and a fried egg. Serve immediately.", timer: null },
    ],
    notes: "Frozen pomegranate seeds scattered on top add a nice sweet-tart crunch if you want to dress it up. Mini cucumbers, sliced thin, are a good addition to the salad too (about 3 mini per English cucumber). For a different direction, swap the garlic powder/smoked paprika for gochugaru, or for garam masala and cumin.",
  },
  {
    id: "fresh-herb-ranch",
    title: "Fresh Herb Ranch Dressing",
    tagline: "Buttermilk ranch thinned out with minced fresh dill, chives & parsley.",
    category: "Dressings & Sauces",
    icon: "jar",
    accent: PALETTE.basil,
    baseServings: 6,
    scalable: false,
    image: "https://images.unsplash.com/photo-1780037382703-c13d292aaf7d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8cmFuY2glMjBkcmVzc2luZyUyMGJvd2x8ZW58MHwwfHx8MTc4NjkzNDA1N3wy&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Allen Y", username: "yanahd" },
    ingredients: [
      { id: "i1", amount: 0.75, unit: "cup", name: "buttermilk" },
      { id: "i2", amount: 0.5, unit: "cup", name: "mayonnaise" },
      { id: "i3", amount: 0.25, unit: "cup", name: "sour cream" },
      { id: "i4", amount: 1, unit: "tsp", name: "lemon juice" },
      { id: "i5", amount: 1, unit: "tbsp", name: "fresh dill, finely minced" },
      { id: "i6", amount: 1, unit: "tbsp", name: "fresh chives, finely minced" },
      { id: "i7", amount: 1, unit: "tbsp", name: "fresh parsley, finely minced" },
      { id: "i8", amount: 0.5, unit: "tsp", name: "garlic powder" },
      { id: "i9", amount: 0.5, unit: "tsp", name: "onion powder" },
      { id: "i10", amount: 0.5, unit: "tsp", name: "salt" },
      { id: "i11", amount: 0.5, unit: "tsp", name: "black pepper" },
    ],
    steps: [
      { id: "s1", title: "Whisk the liquids", content: "Combine the ¾ cup buttermilk, ½ cup mayonnaise, ¼ cup sour cream, and 1 tsp lemon juice in a bowl.", timer: null },
      { id: "s2", title: "Prep the herbs", content: "Finely mince the 1 tbsp each of fresh dill, chives, and parsley so they distribute evenly.", timer: null },
      { id: "s3", title: "Blend everything", content: "Stir the fresh herbs and dry spices (½ tsp each garlic powder, onion powder, salt, and pepper) into the liquid base.", timer: null },
      { id: "s4", title: "Check the thickness", content: "If you want it even thinner, whisk in an extra tablespoon of buttermilk.", timer: null },
      { id: "s5", title: "Rest & chill", content: "Chill in the fridge to let the fresh herb oils infuse before serving.", timer: 1800 },
    ],
    notes: "Fresh herbs are less concentrated than dried — that's why the quantities here run about triple what a dried-herb ranch would use, to keep the flavor vibrant. For a bolder version, try swapping the garlic powder for fresh minced garlic.",
  },
  {
    id: "broccoli-cheddar-fritters",
    title: "Crispy Broccoli Cheddar Fritters with Ranch Salad",
    tagline: "Golden fried fritters, honey Dijon for dipping, ranch salad with pickled shallot on the side.",
    category: "Mains",
    icon: "fritter",
    accent: PALETTE.mustard,
    baseServings: 2,
    allergens: "Milk · Eggs · Wheat",
    image: "https://images.unsplash.com/photo-1767114915965-7abe87d7c7d8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8YnJvY2NvbGklMjBmcml0dGVyc3xlbnwwfDB8fHwxNzg2OTM0MDM2fDI&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Chetanya Sharma", username: "chetanya_designs" },
    ingredients: [
      { id: "i1", amount: 8, unit: "oz", name: "broccoli, florets and stalks minced" },
      { id: "i2", amount: 0.5, unit: "cup", name: "cheddar cheese, shredded" },
      { id: "i3", amount: 82, unit: "g", name: "tempura batter mix" },
      { id: "i4", amount: 1, unit: "tbsp", name: "flour" },
      { id: "i5", amount: 1, unit: "tbsp", name: "Fry Seasoning" },
      { id: "i6", amount: 1, unit: "", name: "shallot, halved, peeled & thinly sliced" },
      { id: "i7", amount: 5, unit: "tsp", name: "white wine vinegar" },
      { id: "i8", amount: 0.5, unit: "tsp", name: "sugar" },
      { id: "i9", amount: 1, unit: "", name: "tomato, diced" },
      { id: "i10", amount: 4, unit: "oz", name: "mixed greens" },
      { id: "i11", amount: 3, unit: "oz", name: "buttermilk ranch dressing" },
      { id: "i12", amount: 1.5, unit: "oz", name: "honey Dijon dressing, for dipping" },
      { id: "i13", amount: 2, unit: "tsp", name: "cooking oil, plus more for frying" },
      { id: "i14", amount: 1, unit: "tsp", name: "salt, plus more to taste" },
      { id: "i15", amount: 0.25, unit: "tsp", name: "black pepper, plus more to taste" },
    ],
    steps: [
      { id: "s1", title: "Prep the broccoli", content: "Wash and dry produce. Mince the 8 oz broccoli florets and stalks. Place in a large microwave-safe bowl with 1 tbsp water, cover with plastic wrap, and microwave until bright green and slightly softened, 2–3 minutes. Halve, peel, and thinly slice the 1 shallot crosswise. Dice the 1 tomato.", timer: 180 },
      { id: "s2", title: "Quick-pickle the shallot", content: "In a small bowl, combine the sliced shallot, 5 tsp white wine vinegar, ½ tsp sugar, and a pinch of salt. Cover with plastic wrap and microwave 30 seconds. Set aside to pickle, stirring occasionally, until ready to use.", timer: 30 },
      { id: "s3", title: "Mix the fritter batter", content: "In a second large bowl, combine the 82 g tempura batter mix, 1 tbsp flour, 1 tbsp Fry Seasoning, ⅓ cup cold water, ½ tsp salt, and pepper until smooth. Stir in the broccoli and ½ cup cheddar until thoroughly combined.", timer: null },
      { id: "s4", title: "Fry the fritters", content: "Heat 2 tsp cooking oil (plus more as needed) in a large pan over medium-high heat. Once hot, add ¼-cup scoops of fritter batter and cook until browned, crisped, and warmed through, 2–4 minutes per side. Don't overcrowd the pan — cook in batches if needed, and lower the heat if they're browning too fast. Transfer to a paper-towel-lined plate and season immediately with salt. Wash and dry the batter bowl.", timer: 240 },
      { id: "s5", title: "Toss the ranch salad", content: "In the bowl used for the fritter batter, toss together the 4 oz mixed greens, tomato, pickled shallot (draining it first), and 3 oz buttermilk ranch dressing. Season with salt and pepper.", timer: null },
      { id: "s6", title: "Plate & serve", content: "Divide the salad and fritters between plates. Serve with the 1.5 oz honey Dijon dressing on the side for dipping.", timer: null },
    ],
    notes: "Allergens: milk, eggs, wheat. Uses the Fry Seasoning and Honey Dijon Dressing recipes also in this cookbook.",
  },
  {
    id: "fry-seasoning",
    title: "Fry Seasoning (Copycat Blend)",
    tagline: "Smoky paprika-garlic-onion blend for fries, roasted veg, and fritters.",
    category: "Seasonings",
    icon: "spice",
    accent: PALETTE.brick,
    baseServings: 6,
    scalable: false,
    image: "https://images.unsplash.com/photo-1625921133217-8d978f7872b8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8cGFwcmlrYSUyMHNwaWNlJTIwYmxlbmR8ZW58MHwwfHx8MTc4NjkzNDAzNnwy&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Towfiqu barbhuiya", username: "towfiqu999999" },
    ingredients: [
      { id: "i1", amount: 2, unit: "tbsp", name: "smoked paprika" },
      { id: "i2", amount: 2, unit: "tbsp", name: "garlic powder" },
      { id: "i3", amount: 2, unit: "tbsp", name: "onion powder" },
      { id: "i4", amount: 1, unit: "tsp", name: "ground cumin (optional)" },
      { id: "i5", amount: 0.5, unit: "tsp", name: "ground coriander (optional)" },
      { id: "i6", amount: 0.25, unit: "tsp", name: "cayenne pepper (optional, for heat)" },
    ],
    steps: [
      { id: "s1", title: "Measure the base", content: "Measure the 2 tbsp smoked paprika, 2 tbsp garlic powder, and 2 tbsp onion powder into a small bowl.", timer: null },
      { id: "s2", title: "Add optional depth", content: "Stir in the 1 tsp cumin, ½ tsp coriander, and/or ¼ tsp cayenne if using, for a warmer or spicier blend.", timer: null },
      { id: "s3", title: "Whisk to combine", content: "Whisk everything together until evenly combined, breaking up any clumps.", timer: null },
      { id: "s4", title: "Store", content: "Transfer to an airtight jar or container. Keeps up to 6 months in a cool, dark pantry.", timer: null },
    ],
    notes: "This is a homemade stand-in for HelloFresh's proprietary Fry Seasoning — they don't publish the exact ratio, but it's built around paprika, garlic powder, and onion powder. Use about 1 tbsp per 1.5 lbs of potatoes or vegetables before roasting or air frying. Used in the broccoli cheddar fritters recipe.",
  },
  {
    id: "honey-dijon-dressing",
    title: "Honey Dijon Dressing",
    tagline: "Whisked mustard-honey vinaigrette, ready in five minutes.",
    category: "Dressings & Sauces",
    icon: "dijonjar",
    accent: PALETTE.mustard,
    baseServings: 6,
    scalable: false,
    image: "https://images.unsplash.com/photo-1638324396220-432156cd9303?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8aG9uZXklMjBtdXN0YXJkJTIwZHJlc3Npbmd8ZW58MHwwfHx8MTc4NjkzNDAzNnwy&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Addilyn Ragsdill", username: "clockwork_lemon" },
    ingredients: [
      { id: "i1", amount: 0.25, unit: "cup", name: "Dijon mustard" },
      { id: "i2", amount: 0.25, unit: "cup", name: "honey" },
      { id: "i3", amount: 2, unit: "tbsp", name: "apple cider vinegar (or lemon juice)" },
      { id: "i4", amount: 0.33, unit: "cup", name: "olive oil" },
      { id: "i5", amount: 0.25, unit: "tsp", name: "salt" },
      { id: "i6", amount: 0.25, unit: "tsp", name: "black pepper" },
    ],
    steps: [
      { id: "s1", title: "Whisk the base", content: "Whisk together the ¼ cup Dijon mustard, ¼ cup honey, and 2 tbsp apple cider vinegar until smooth.", timer: null },
      { id: "s2", title: "Emulsify the oil", content: "Slowly drizzle in the ⅓ cup olive oil while whisking continuously, so it emulsifies instead of separating.", timer: null },
      { id: "s3", title: "Season & taste", content: "Season with ¼ tsp salt and ¼ tsp black pepper. Taste and adjust — more honey for sweeter, more vinegar for tang.", timer: null },
      { id: "s4", title: "Store", content: "Keep in a sealed jar in the fridge for up to a week. Give it a shake before using, since it can separate slightly when cold.", timer: null },
    ],
    notes: "Makes about 3/4 cup. Doubles nicely as both a dressing and a dip — it's the dipping sauce for the broccoli cheddar fritters recipe.",
  },
  {
    id: "spaghetti-aglio-olio-anchovy-chili",
    title: "Spaghetti Aglio e Olio with Anchovies & Fresno Chili",
    tagline: "A bold Italian classic with melted anchovies, golden garlic, and fruity Fresno heat.",
    category: "Mains",
    icon: "blank",
    accent: PALETTE.brick,
    baseServings: 1,
    allergens: "Fish · Milk · Wheat",
    image: "https://images.unsplash.com/photo-1693820206774-d4a769355142?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8c3BhZ2hldHRpJTIwYWdsaW8lMjBvbGlvJTIwZ2FybGljJTIwcGFzdGF8ZW58MHwwfHx8MTc4NjkzNDAzN3wy&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Imad 786", username: "imad8321" },
    ingredients: [
      { id: "i1", amount: 80, unit: "g", name: "spaghetti" },
      { id: "i2", amount: 56, unit: "g", name: "Crown Prince flat anchovies (whole tin)" },
      { id: "i3", amount: 5, unit: "cloves", name: "garlic, thinly sliced" },
      { id: "i4", amount: 2, unit: "", name: "Fresno chili peppers, thinly sliced" },
      { id: "i5", amount: 3, unit: "tbsp", name: "olive oil" },
      { id: "i6", amount: 1, unit: "tsp", name: "tomato paste" },
      { id: "i7", amount: 0.5, unit: "cup", name: "pasta water, reserved before draining" },
      { id: "i8", amount: 2, unit: "tbsp", name: "Parmesan, freshly grated" },
      { id: "i9", amount: 1, unit: "tbsp", name: "fresh parsley, chopped (optional)" },
      { id: "i10", amount: 1, unit: "pinch", name: "black pepper" },
    ],
    steps: [
      { id: "s1", title: "Cook the pasta", content: "Cook the 80 g spaghetti in a large pot of well-salted boiling water until al dente, about 8–9 min. Before draining, scoop out ½ cup pasta water — don't skip this!", timer: 480 },
      { id: "s2", title: "Slowly cook the garlic", content: "In a wide pan, warm the 3 tbsp olive oil over medium-low. Add the 5 sliced garlic cloves and cook slowly until golden. Do not rush — low and slow is the key.", timer: null },
      { id: "s3", title: "Melt in the anchovies", content: "Add the 56 g anchovies to the pan and stir until they completely dissolve into the oil, about 1–2 min. The base should look dark and deeply savory.", timer: 90 },
      { id: "s4", title: "Add tomato paste", content: "Add a splash of the reserved pasta water immediately to stop the garlic cooking. Then add the 1 tsp tomato paste and stir into the oil for 1 min.", timer: 60 },
      { id: "s5", title: "Add the chili", content: "Add the 2 sliced Fresno chilis and cook 1 min until they just soften and release their heat into the oil.", timer: 60 },
      { id: "s6", title: "Toss the pasta", content: "Add drained spaghetti to the pan. Pour in another splash of pasta water and toss vigorously for 1–2 min until the sauce is silky and coats every strand.", timer: 90 },
      { id: "s7", title: "Finish & serve", content: "Take the pan completely off heat. Add the 2 tbsp Parmesan and a pinch of black pepper, toss again. Finish with the parsley if using. Serve immediately.", timer: null },
    ],
    notes: "The garlic can go from golden to burnt fast — keep the heat low and watch it closely. Pasta water is the secret to a silky sauce — the starch emulsifies the oil. Parmesan always goes in off heat or it'll clump.",
  },
  {
    id: "mediterranean-farro-salad",
    title: "Mediterranean Farro Salad",
    tagline: "Nutty pearled farro with cucumber, tomatoes, olives, and a bright lemon-oregano dressing.",
    category: "Salads",
    icon: "blank",
    accent: PALETTE.basil,
    baseServings: 1,
    image: "https://images.unsplash.com/photo-1786101821619-eeac3b3126e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8M3x8bWVkaXRlcnJhbmVhbiUyMGZhcnJvJTIwZ3JhaW4lMjBzYWxhZHxlbnwwfDB8fHwxNzg3MDE5NTc1fDI&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Teo Zac", username: "teo" },
    ingredients: [
      { id: "i1", amount: 0.25, unit: "cup", name: "pearled farro" },
      { id: "i2", amount: 0.5, unit: "cup", name: "water or chicken broth (for cooking farro)" },
      { id: "i3", amount: 0.33, unit: "cup", name: "English cucumber, diced" },
      { id: "i4", amount: 0.33, unit: "cup", name: "cherry tomatoes, halved" },
      { id: "i5", amount: 2, unit: "tbsp", name: "kalamata olives, sliced" },
      { id: "i6", amount: 1, unit: "tbsp", name: "shallot, finely diced" },
      { id: "i7", amount: 1, unit: "tbsp", name: "fresh parsley, chopped" },
      { id: "i8", amount: 2, unit: "tbsp", name: "sharp cheddar, shredded (optional)" },
      { id: "i9", amount: 0.5, unit: "", name: "lemon, juiced" },
      { id: "i10", amount: 1, unit: "tbsp", name: "olive oil" },
      { id: "i11", amount: 0.5, unit: "", name: "garlic clove, minced" },
      { id: "i12", amount: 0.25, unit: "tsp", name: "dried oregano" },
      { id: "i13", amount: 0.125, unit: "tsp", name: "salt" },
      { id: "i14", amount: 1, unit: "", name: "pinch black pepper" },
    ],
    steps: [
      { id: "s1", title: "Cook the farro", content: "Bring the ½ cup water or broth to a boil, add the ¼ cup farro, reduce to a simmer, and cook until tender, about 15–20 minutes. Drain any excess liquid and let cool slightly.", timer: 1200 },
      { id: "s2", title: "Prep the vegetables", content: "While the farro cooks, dice the ⅓ cup cucumber, halve the ⅓ cup cherry tomatoes, finely dice the 1 tbsp shallot, and chop the 1 tbsp parsley.", timer: null },
      { id: "s3", title: "Make the dressing", content: "Whisk together the juice of ½ lemon, 1 tbsp olive oil, ½ minced garlic clove, ¼ tsp dried oregano, ⅛ tsp salt, and a pinch of pepper.", timer: null },
      { id: "s4", title: "Dress the warm farro", content: "Toss the still-warm farro with the dressing so it soaks in while cooling.", timer: null },
      { id: "s5", title: "Combine", content: "Fold in the cucumber, tomatoes, 2 tbsp kalamata olives, shallot, parsley, and 2 tbsp cheddar if using. Taste and adjust salt, pepper, or lemon.", timer: null },
      { id: "s6", title: "Serve", content: "Serve warm, at room temperature, or chilled.", timer: null },
    ],
    notes: "Swap in a little shredded sharp cheddar instead of feta — Tillamook works well here, though it's optional. Parsley keeps things classically Mediterranean, but dill or chives would both work if you want to switch it up. Dressing the farro while it's still warm helps it soak up more flavor. Keeps in the fridge for 3–4 days.",
  },
  {
    id: "broccoli-parmesan-pasta",
    title: "Broccoli Parmesan Pasta with Blistered Tomatoes & Chili Crunch",
    tagline: "Charred broccoli, blistered cherry tomatoes, and a Parmesan pan sauce, finished with a spoonful of chili crunch.",
    category: "Mains",
    icon: "blank",
    accent: PALETTE.basil,
    baseServings: 1,
    allergens: "Milk · Wheat",
    image: "https://images.unsplash.com/photo-1670744030620-82776d123835?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8MXx8YnJvY2NvbGklMjBwYXN0YSUyMHBhcm1lc2FuJTIwdG9tYXRvZXN8ZW58MHwwfHx8MTc4Nzc5Mzk1Nnwy&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Shintaro Kikuchi", username: "shinsk8" },
    ingredients: [
      { id: "i1", amount: 3, unit: "oz", name: "short pasta (fusilli, orecchiette, or shells)" },
      { id: "i2", amount: 1, unit: "cup", name: "broccoli florets" },
      { id: "i3", amount: 0.5, unit: "cup", name: "cherry tomatoes, halved" },
      { id: "i4", amount: 1, unit: "", name: "small shallot, thinly sliced" },
      { id: "i5", amount: 2, unit: "cloves", name: "garlic, minced" },
      { id: "i6", amount: 2, unit: "tbsp", name: "olive oil" },
      { id: "i7", amount: 0.33, unit: "cup", name: "grated Parmesan, plus more for serving" },
      { id: "i8", amount: 1.5, unit: "tsp", name: "Momofuku Chili Crunch" },
      { id: "i9", amount: 0.25, unit: "tsp", name: "salt" },
      { id: "i10", amount: 1, unit: "pinch", name: "black pepper" },
    ],
    steps: [
      { id: "s1", title: "Boil the pasta", content: "Bring a pot of salted water to a boil. Cook the 3 oz pasta until al dente according to package directions. Reserve about ½ cup pasta water, then drain.", timer: 600 },
      { id: "s2", title: "Char the broccoli", content: "Heat 1 tbsp olive oil in a large skillet over medium-high heat. Add the 1 cup broccoli florets and cook, tossing occasionally, until browned in spots and crisp-tender. Season with a pinch of salt. Remove from the pan.", timer: 360 },
      { id: "s3", title: "Sauté shallot, garlic & tomatoes", content: "Add the remaining 1 tbsp oil to the pan. Sauté the shallot for 2 minutes until softened, then add the 2 minced garlic cloves and cook 30 seconds until fragrant. Add the ½ cup cherry tomatoes and cook until blistered and starting to burst.", timer: 240 },
      { id: "s4", title: "Toss it all together", content: "Return the broccoli to the pan with the drained pasta and a splash of reserved pasta water. Toss well, then stir in the ⅓ cup Parmesan until it melts into a light, glossy sauce. Season with the remaining salt and pinch of pepper to taste.", timer: null },
      { id: "s5", title: "Finish & serve", content: "Plate the pasta and top with 1½ tsp Momofuku Chili Crunch and extra Parmesan if you like.", timer: null },
    ],
    notes: "Chili crunch adds garlicky, crunchy heat on top — start with a spoonful and add more to taste. Orecchiette or shells hold the sauce a little better than fusilli if you have a choice.",
  },
  {
    id: "oma-rhabarberkuchen-baiser",
    title: "Oma's Rhubarb Cake with Meringue",
    tagline: "A juicy German rhubarb cake baked from Oma's original recipe, topped with a pillowy toasted meringue.",
    category: "Desserts",
    icon: "cake",
    accent: PALETTE.mustard,
    baseServings: 12,
    scalable: false,
    allergens: "Milk · Eggs · Wheat",
    sourceUrl: "https://www.malteskitchen.de/rhabarberkuchen-baiser-oma/",
    image: "https://images.unsplash.com/photo-1623596627064-bbd32c626478?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3wxMDE3MjIwfDB8MXxzZWFyY2h8NHx8cmh1YmFyYiUyMGNha2UlMjBtZXJpbmd1ZXxlbnwwfDB8fHwxNzg3Nzk0NzEzfDI&ixlib=rb-4.1.0&q=80&w=1080",
    imageCredit: { name: "Maximilian Zahn", username: "_iammax" },
    ingredients: [
      { id: "i1", amount: 500, unit: "g", name: "rhubarb, cut into ~1 cm pieces" },
      { id: "i2", amount: 2, unit: "tbsp", name: "sugar (for the rhubarb)" },
      { id: "i3", amount: 1, unit: "tbsp", name: "cornstarch (for the rhubarb)" },
      { id: "i4", amount: 200, unit: "g", name: "butter, room temperature" },
      { id: "i5", amount: 100, unit: "g", name: "sugar (for the batter)" },
      { id: "i6", amount: 4, unit: "", name: "egg yolks (whites reserved for the meringue)" },
      { id: "i7", amount: 3, unit: "", name: "eggs" },
      { id: "i8", amount: 200, unit: "g", name: "all-purpose flour (type 405)" },
      { id: "i9", amount: 1, unit: "packet", name: "baking powder" },
      { id: "i10", amount: 1, unit: "pinch", name: "salt (for the batter)" },
      { id: "i11", amount: 75, unit: "ml", name: "milk" },
      { id: "i12", amount: 4, unit: "", name: "egg whites (reserved from above)" },
      { id: "i13", amount: 200, unit: "g", name: "sugar (for the meringue)" },
      { id: "i14", amount: 1, unit: "pinch", name: "salt (for the meringue)" },
    ],
    steps: [
      { id: "s1", title: "Prep the pan & oven", content: "Line the bottom of a 26 cm (10-inch) springform pan with parchment paper and grease the sides halfway up with butter. Preheat the oven to 175°C (350°F) top/bottom heat.", timer: null },
      { id: "s2", title: "Cream the butter & sugar", content: "Beat the 200 g butter with 100 g sugar for 10 minutes with a stand mixer until light, pale, and fluffy.", timer: 600 },
      { id: "s3", title: "Prep the rhubarb", content: "Meanwhile, wash the rhubarb and cut into small pieces, about 1 cm long. Toss the 500 g rhubarb with 2 tbsp sugar and set aside.", timer: null },
      { id: "s4", title: "Separate the eggs", content: "Separate 4 eggs, setting the egg whites aside for the meringue. Mix the 200 g flour, 1 packet baking powder, and a pinch of salt.", timer: null },
      { id: "s5", title: "Build the batter", content: "Add the 4 egg yolks and the remaining 3 whole eggs to the butter mixture and mix well.", timer: null },
      { id: "s6", title: "Finish the batter", content: "Add the flour mixture and 75 ml milk to the bowl and stir briefly until a smooth, homogeneous batter forms. Pour into the springform pan and smooth the top.", timer: null },
      { id: "s7", title: "Top with rhubarb & first bake", content: "Drain off any liquid that has collected from the rhubarb. Stir 1 tbsp cornstarch into the rhubarb, then spread it evenly over the batter. Bake for 30 minutes on the lowest rack (important!).", timer: 1800 },
      { id: "s8", title: "Whip the meringue", content: "After 25 minutes of baking, beat the 4 egg whites with a pinch of salt. Once foamy, slowly stream in the remaining 200 g sugar and beat until stiff, glossy peaks form — about 5 minutes total.", timer: 300 },
      { id: "s9", title: "Top with meringue", content: "Once the 30 minutes is up, remove the cake from the oven and spread the meringue on top using two spoons, leaving a border of about 1.5 cm — the meringue expands as it bakes and shouldn't touch the pan sides. Use the spoons to create a wave pattern or peaks.", timer: null },
      { id: "s10", title: "Second bake", content: "Bake again for 25–30 minutes on the lowest rack (important!) at 175°C (350°F) top/bottom heat. The meringue should turn a light beige — watch closely near the end so it doesn't get too dark or scorch.", timer: 1800 },
    ],
    notes: "Bake on the lowest oven rack both times so the meringue doesn't over-brown before it's fully set. Watch the last few minutes closely — the meringue should be light beige, never dark or blackened. Adapted from Oma's original recipe via Malte's Kitchen.",
  },
];
